### ISSUE TITLE
Placeholders dont always work

### ISSUE THREAD

**Issue by wildmaster84** [ArVdC/TimeManager#35]
while trying to create a custom gui to display the time, for some reason the placeholders just dont work. they work for boss bars and in chat but not in a gui or when trying to log to console.

![image](https://github.com/user-attachments/assets/8c8bc76e-b530-4ab8-b379-cdf245616b1c)

**Comment by ArVdC** [comment]
Have you enabled placeholders for commands in the config.yml file ?
```
placeholders:
  PlaceholderAPI: 'false'
  MVdWPlaceholderAPI: 'false'
  inChatEnable: 'true'
  -> inCommandsEnable: 'true'
```

**Comment by wildmaster84** [comment]
yeah, its hard to tell from the image, but the placeholders are shown working in the bossbar but not in the custom gui

**Comment by ArVdC** [comment]
I'm not entirely sure, but maybe the command sender is not recognized.
Could you do a test and tell me what the sender of your GUI corresponds to?
To work properly Timemanager needs it, because in my code there is :
`CommandSender sender = e.getSender();`
`if (sender instanceof ????) { ... };`
You can take a look at : [https://github.com/ArVdC/TimeManager/blob/master/src/net/vdcraft/arvdc/timemanager/placeholders/ConsoleCommandHandler.java](https://github.com/ArVdC/TimeManager/blob/master/src/net/vdcraft/arvdc/timemanager/placeholders/ConsoleCommandHandler.java)

**Comment by wildmaster84** [comment]
i dont interact with any entity when trying to use the placeholders in the gui.

![image](https://github.com/user-attachments/assets/8bfa2dac-abb5-49e2-81f3-4987ba648186)

Is there a more direct way to get the values via an api?

**Comment by ArVdC** [comment]
I didn't design the plugin as an API but I think this might work :
First `import net.vdcraft.arvdc.timemanager.mainclass.PlaceholdersHandler`
Then use this method `replacePlaceholder(String placeholder, String world, String lang, Player p)`
-> The 'Player' value can certainly be retrieved since there must be a player manipulating the inventory/GUI. But please note 'Player' can also be _null_.
-> On the other hand, the 'world' name **must** be retreived in one way or another.

e.g.
`meta.setDisplayName(ChatColor.WHITE + replacePlaceholder(tm_hours12, worldname, en_US, null) + ":" + replacePlaceholder(tm_minutes, worldname, en_US, null) + replacePlaceholder(tm_ampm, worldname, en_US, null) + ", " + replacePlaceholder(tm_dayname, worldname, en_US, null));`

**Comment by ArVdC** [comment]
Have you tried ?

**Comment by wildmaster84** [comment]
just tried and seems to have the same issue, ik it looks horrible xd

![image](https://github.com/user-attachments/assets/2a6572eb-f91f-45a6-8a7d-4316227fe367)

**Comment by wildmaster84** [comment]
i figured it out, i had to replace the placeholders all at once

![image](https://github.com/user-attachments/assets/249ebc89-9dcb-4360-80c0-fb7fd716796c)
![image](https://github.com/user-attachments/assets/accf4a11-c540-41d3-b4e0-977ecddcb127)
